---
output:
  knitrBootstrap::bootstrap_document:
    title: "Compare transcript divergence with translation divergence"
    theme: default
---

Differential divergence analysis
=================================

```{r run_author, results='asis', echo=FALSE}
email <- "<a href='mailto:joyce.hsiao1@gmail.com'>Joyce Hsiao</a>"
cat(paste("Author:", email))
```


```{r run_date, results='asis', echo=FALSE}
#last_update = format(Sys.time(), "(<time>%Y-%m-%d</time>)")
last_update <- Sys.time()
cat(paste("Last updated:", last_update))
```


```{r knitr_settings, include=FALSE, echo=FALSE}
library(knitr)
opts_knit$set(progress = TRUE, verbose = TRUE)
opts_chunk$set(message = FALSE, warning = FALSE, eval = TRUE, echo = TRUE,
              bootstrap.panel = FALSE, bootstrap.show.code = FALSE)
#fig.width = 800/96, fig.height = 800/96, dpi = 96,
```


Goal
=====


```{r load_packages}
library(Biobase)

## Set working directories 
dir <- "../"
figdir <- file.path(dir,"figures")
rdadir <- file.path(dir,"rdas")
datadir <- file.path(dir, "data")

## Use broman package for colors
require(broman)
crayon <- brocolors("crayons")

## Load customized packages
require(devtools)
require(Humanzee)
```




Human versus Chimp
==================


## RNA and Ribo divergence

```{r, eval = F}
load(file.path(rdadir,"eSetRRP.rda"))

## eSetRRP.RP.Q.log2 includes standardizd RPKM values
eSet <- eSetRRP.RP.Q.log2[ , eSetRRP.RP.Q.log2$species != "rhesus" & 
        eSetRRP.RP.Q.log2$seqData != "protein"]
res.riborna <- interact2way(eSet)
save(res.riborna,file=file.path(rdadir,"TEnew.rda"))
```



Other inter-species comparisons
===============================


## RNA and Ribo divergence

```{r, eval = F}
load(file.path(rdadir,"eSetRRP.rda"))

## eSetRRP.RP.Q.log2 includes standardizd RPKM values
## Human versus Rhesus
eSet_human_rhesus <- eSetRRP.RP.Q.log2[ , eSetRRP.RP.Q.log2$species != "chimp" & 
                     eSetRRP.RP.Q.log2$seqData != "protein"]
res.riborna_human_rhesus <- interact2way(eSet_human_rhesus)

## Chimp versus Rhesus
eSet_chimp_rhesus <- eSetRRP.RP.Q.log2[ , eSetRRP.RP.Q.log2$species != "human" & 
                     eSetRRP.RP.Q.log2$seqData != "protein"]
res.riborna_chimp_rhesus <- interact2way_full_buffer(eSet_chimp_rhesus) 

save(res.riborna_human_rhesus, res.riborna_chimp_rhesus,
     file = file.path(rdadir,"TE_other_interspecies.rda"))

```




